name: digital_menu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  qr_flutter: ^4.1.0
  svg_flutter: ^0.0.1
  intl: ^0.18.1
  http: ^1.1.0
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  google_fonts: ^6.1.0
  firebase_storage: ^11.3.1
  file_picker: ^6.0.0
  mime: ^1.0.4
  universal_platform: ^1.0.0+1
  dio: ^5.4.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

