// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOjgfxEc3Sxv8V5rd5eZ_8FCU2ca9yiJo',
    appId: '1:972789726054:web:96dc5190bb102ad2c426a7',
    messagingSenderId: '972789726054',
    projectId: 'digital-menu-73083',
    authDomain: 'digital-menu-73083.firebaseapp.com',
    storageBucket: 'digital-menu-73083.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUuZAHmw2cztue1G6bO0M1T3Ebf0CiZgc',
    appId: '1:972789726054:android:a20e2e09c320bb5fc426a7',
    messagingSenderId: '972789726054',
    projectId: 'digital-menu-73083',
    storageBucket: 'digital-menu-73083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IXjH3HKbuJQJGa9-Omrg8h5LwRRjQ-8',
    appId: '1:972789726054:ios:91cefbba936c5cc6c426a7',
    messagingSenderId: '972789726054',
    projectId: 'digital-menu-73083',
    storageBucket: 'digital-menu-73083.appspot.com',
    iosBundleId: 'com.example.digitalMenu',
  );
}
